version: 2.0
jobs:
 build:
   docker:
     - image: circleci/ruby:2.1
   steps:
     - checkout
     - run:
        name: Install Dependencies
        command: |
          gem install bundler --no-rdoc --no-ri -v 1.11.2
          bin/setup
     - run:
        name: Run Tests
        command: bundle exec rake spec
