version: 2.0
jobs:
 build:
   docker:
     - image: circleci/ruby:2.1
   steps:
     - checkout
     - run:
        name: Install Dependencies
        command: |
          gem install bundler --no-rdoc --no-ri -v 1.11.2
          bin/setup
     - run:
        name: Run Tests
        command: bundle exec rake spec
 deploy:
   docker:
     - image: circleci/ruby:2.1
   steps:
     - checkout
     - run:
        name: Install Dependencies
        command: |
          gem install bundler --no-rdoc --no-ri -v 1.11.2
          bin/setup
     - run:
        name: Setup Rubygems
        command: bash .circleci/setup-rubygems.sh
     - run:
        name: Publish to Rubygems
        command: bundle exec rake release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              tags:
                only: /.*/
            branches:
              ignore: /.*/
